### ISSUE TITLE
Intermittent "focus stealing"

### ISSUE THREAD

**Issue by Nightblade** [DavidFW1960/Aussie-Broadband-Usage-Meter#27]
For approximately the last 3 months this otherwise excellent skin has been intermittently "focus stealing" when it does its 10-minute update, causing games running in full-screen mode to "alt-tab" to the desktop for seemingly no reason.

Log shows nothing out of the ordinary:  [ABB-DebugLog-ABBUsage-ABB-2020-07-26.txt](https://github.com/DavidFW1960/Aussie-Broadband-Usage-Meter/files/5011523/ABB-DebugLog-ABBUsage-ABB-2020-07-26.txt)

I suspect it *might* be something to do with running the VB script, but I have been unable to reproduce the problem with a test skin and a script that sleeps for 2 seconds.

I'm using Rainmeter 4.3.1.3321 (64-bit).

**Comment by DavidFW1960** [comment]
If you manage settings for rainmeter and open settings, check the 
```
AlwaysOnTop=0
```
For the skin...

**Comment by Nightblade** [comment]
Just checked, it's set to 0.

**Comment by Nightblade** [comment]
Additional information:  I just noticed my windows pointer briefly changes to the "busy" pointer when the update occurs (which I changed just now to 20 seconds for testing).

**Comment by DavidFW1960** [comment]
Not sure why it would do that.. The .ini file for the skin determines the update interval (how often the VB script runs). Not sure what to say as I have not seen this problem but perhaps because I'm not running critical real-time apps... You might need to disable/quit rainmeter while gaming..

**Comment by protogen** [comment]
I've read of this occurring with Rainmeter going back as far as 2012.  The "focus stealing" usually only occurs when the system is heavily loaded.

Normally, Rainmeter does its periodic update of all skins faster than the periodic scan performed by the OS window manager (of whichever OS you are running).  However, if the system is heavily loaded then the Rainmeter periodic update can sometimes run long/late (i.e. process is waiting for CPU time) enough that the OS window manager notices and switches focus.

We're talking about a difference of milliseconds here so that's why it occurs intermittently.  It's not a fault of Rainmeter, or even the skin (although skins with external scripts do increase the probability of it occurring).  It's just a coincidence of factors combining to create the right conditions.

That said, I've never had this happen to me personally, however just like DavidFW1960 I do not run real-time apps, nor do I play games.

I'm using Rainmeter 4.3.0.3298 (64-bit).

**Comment by DavidFW1960** [comment]
Thanks @protogen I was thinking overnight that maybe @Nightblade could ask on the rainmeter forum if anyone has any ideas about this...

**Comment by Nightblade** [comment]
(As a temporary workaround I've added a Task Scheduler item that runs the VBS once an hour, and commented out the appropriate lines in the Rainmeter skin.)

**Comment by Nightblade** [comment]
Well, I seem to have fixed it by accident!  :)  An extra pair of double-quotes around the script-call does the trick:

```IfEqualAction=[" "#@#Scripts\ABB-Usage.vbs" "#CURRENTCONFIG#" "#CURRENTFILE#" "]```

**Comment by protogen** [comment]
That is very interesting.  I've checked the Rainmeter manual and can find no reference to this (link below).

It mentions single sets of double quotes and triple sets of double quotes (magic quotes), however inner/outer sets are not mentioned nor are there any examples of this shown.

https://docs.rainmeter.net/manual/skins/option-types/#Action

If I had to guess, I'd say the inner sets of double quotes (around the script name and each argument) are being passed through to cmd.exe.  But even if this is occurring, I can't see how that would have any affect on execution.

I'll keep thinking about it.  :-)

**Comment by DavidFW1960** [comment]
@protogen is there any reason not to amend the ini file calling the script with this change? Can you see any unintended consequences?
@Nightblade are you using my abb.ini now or have you amended your original one to use the new scripts?

If there's no reason not to I'm happy to do a new release with this change (however I'm not with ABB now so I can't test it and neither is @protogen so we'd be relying on others..)

**Comment by Nightblade** [comment]
I'm talking to some of the Rainmeter wizards in the unofficial Discord, and will update here when I know anything more.

File versions I'm currently using:

; Rainmeter configuration file
; Updated August 6th, 2019
Version=0.82

' Description: Backend script for ABBUsage Rainmeter skin by Big Kahuna
' Author: Protogen at whirlpool (skin by Big Kahuna)
' Version: 3.5.0
' Date: 5 Aug 2019

**Comment by protogen** [comment]
@DavidFW1960 It's your call, but I tend to be on the cautious side with strange issues like this, so I'd recommend not making the change just yet.

I still can't see how this could have any affect on execution.  Since @Nightblade is the only person experiencing this issue (as far as we know), I think it would be worth waiting a while to let @Nightblade test this longer, just to be sure.

@Nightblade If you could continue to test with the extra double quotes and also without (to confirm the effect) that would be helpful.

**Comment by DavidFW1960** [comment]
agreed... I'm more of a thrill seeker.. no harm, no foul but I agree with you....

**Comment by Nightblade** [comment]
According to Discord user Corvust#9001 this is actually the correct syntax (triple-double-quotes):
```
IfEqualAction=[""" "#@#Scripts\ABB-Usage.vbs" "#CURRENTCONFIG#" "#CURRENTFILE#" """]
```
Corvust also mentioned that they didn't know how the original line even worked.

I can confirm that removing the triple-double-quotes reliably causes focus-stealing for me.

**Comment by protogen** [comment]
@Nightblade No, I'm sorry, that is definitely incorrect.  Triple double quotes (magic quotes) will cause everything between them to be passed as literals.  It says this clearly in the manual (see the link I provided in an earlier post above).

Doing this means the script won't execute because the variables `#@#`, `#CURRENTCONFIG#` and `#CURRENTFILE#` will not be resolved to their current values, instead they will be passed as literal strings (i.e. exactly as quoted).  This also explains why focus-stealing is not occurring - the script is not actually running.

Also, Corvust's comment "didn't know how the original line even worked" is very strange.  The original syntax of the line follows the manual and the examples provided therein.

**Comment by DavidFW1960** [comment]
Hmm.... @Nightblade can you confirm the script is actually running (and the data is updating)? Damn I just pushed this...

**Comment by DavidFW1960** [comment]
I just reverted the commits. I'll leave 0.83 there for now while awaiting more clarification

**Comment by protogen** [comment]
@DavidFW1960 I tested it before I responded.  The script does not execute.  I checked using multiple methods (data files, debug log, process monitoring).

**Comment by Nightblade** [comment]
Apologies, @protogen is 100% correct, the script is not running.

I'll keep searching for a fix.  Thanks.

**Comment by DavidFW1960** [comment]
I guess it not running explains why it 'fixes' it... 

> Corvust's comment "didn't know how the original line even worked" is very strange

Right eh... even stranger now.
