### ISSUE TITLE
Error "RegExp matching error (-1)" since start of monthly cycle

### ISSUE THREAD

**Issue by subi75** [DavidFW1960/Aussie-Broadband-Usage-Meter#29]
Since my monthly billing cycle restarted the skin has not been updating correctly (no usage level, the days remaining is the number of days left in the calendar month  which is not my monthly cycle remaining days, data used is always 0 / 0Gb, etc.
I have reset the skin using the VBS script and reconfigured it but still getting the same errors. It also is not reporting on the skin for the last update date/time, the registered account ID or the rollover date/time.
Within the Rainmeter log it is reported continually the error "RegExp matching error (-1)".
After resetting the skin with the clear VBS script, I had the additional errors "(Fetch error) The system cannot find the path specified. (Errorcode=3)" occur twice for "[MeasureABB]" and once for "[MeasureOptions]".
I also received a "[PercentUsedData]  Calc: Division by 0" error, which I can only assume is because it cannot retrieve the data from ABB's servers.

I suspect possibly ABB have changed something at their end which is now blocking the skin from working, as this has been working fine up until this month's cycle started.
Skin version in use - 0.82
Rainmeter version - 4.5.13.3632 (64bit)
OS - Win11 64bit

**Comment by protogen** [comment]
I'm the author of the VBScript part of the Aussie Broadband Usage Meter.  I've just done a clean install of v0.82 (providing my username/password and choosing skin look).  The skin is working correctly (without error) for me (screenshot below).

![image](https://user-images.githubusercontent.com/3028907/163723628-633b8c16-d915-4057-bb5f-92aeafe4c1e1.png)

That said, I have noticed that the usage data (provided by ABB) has not been updated since the end of Saturday 16th (just a little over 1 day ago).  My usage data json file contains the line below (and the skin also shows this date/time).  I'm hoping this is just a failure at ABB which they will soon rectify.

`"lastUpdated": "2022-04-16 23:59:59"`

Even though the usage data is old, the skin is still able to obtain an auth cookie, download the usage data and display the usage information on the skin without error.

The only suggestion I can make is to
1. Unload the skin
2. Perform a clean (using ABB-Clean.vbs)
3. Reload the skin (which will launch skin setup)

Rainmeter version - 4.5.5.3565 (64-bit)
OS - Win10 x64

**Comment by subi75** [comment]
> 
> The only suggestion I can make is to
> 
>     1. Unload the skin
> 
>     2. Perform a clean (using ABB-Clean.vbs)
> 
>     3. Reload the skin (which will launch skin setup)

Yup did this already. I even deleted the entire ABB Skin folder (%UserProflile%\Documents\Rainmeter\Skins\ABBUsage) plus also tracked down the other configuration file folder it uses (located at %AppData%\Roaming\Rainmeter-ABB\ABBUsage) and deleted that folder as well whilst RainMeter was not running plus manually removed the ABBUsage reference from the rainmeter.ini file to ensure I had a "clean" config, relaunched RainMeter and reinstalled the skin (from a fresh download from Github even tho its the same version), but still no change.

I checked the ABB-Usage.json file, and the LastUpdated field is "null", regardless of how many times I attempt to force a refresh 

I will also note that regardless of what account I set it to, it still appeared to retrieve a valid cookie with an expiry date 12 months after the time of retrieving it (eg expiry 18th Apr 2023), as per the details within %AppData%\Roaming\Rainmeter-ABB\ABBUsage\ABB-Auth.json

Below are log files from the PC (both Rainmeter's own log, and the ABB debug log) for further info as it will show the details including when I added ABBUsage back into Rainmeter. Note - I've modified the log data changing profile path to system variables for privacy reasons.

[ABB-DebugLog-ABBUsage-ABB-2022-04-18.txt](https://github.com/DavidFW1960/Aussie-Broadband-Usage-Meter/files/8503432/ABB-DebugLog-ABBUsage-ABB-2022-04-18.txt)

RainMeter Debug log captured during initial install. I had disabled RainMeter debug before reinitalizing ABBUsage as per above ABB log.
[Rainmeter.log](https://github.com/DavidFW1960/Aussie-Broadband-Usage-Meter/files/8503434/Rainmeter.log)

**Comment by protogen** [comment]
Thanks for the further details and the debug log.  The extra info you've provided should allow me to work out what's going on.  I'll have a look at it now and get back to you when I know more.

**Comment by protogen** [comment]
I've just walked through your entire debug log, following along in the code as I went.  My conclusion is your error is being caused by bad data provided by Aussie Broadband.

The debug log shows that everything in the code is working correctly.  A valid cookie is obtained.  Your ABB Service ID is requested, provided and determined correctly.  Your skin options are saved correctly.  The code sends a request for current usage data (to ABB) and data is returned (by ABB to the code).  However the values in the returned usage data are garbage.  They are zeros and nulls instead of valid values (see below).

Your usage data:
`{"usedMb":0,"downloadedMb":0,"uploadedMb":0,"daysTotal":30,"daysRemaining":26,"remainingMb":null,"lastUpdated":null}`

My usage data:
`{"usedMb":77967,"downloadedMb":67997,"uploadedMb":9970,"remainingMb":422033,"daysTotal":30,"daysRemaining":16,"lastUpdated":"2022-04-19 15:54:52"}`

The request for usage data is constructed correctly and requested correctly by the code (using a valid cookie).  Why ABB are returning invalid data to you is not something I can answer.

The Rainmeter errors you are getting ("RegExp matching error (-1)", "[PercentUsedData] Calc: Division by 0", etc) are a result of the invalid data (which you had already assumed correctly).

The only suggestion I have left is for you to contact ABB, either through support or on their Discord channel, and ask them to investigate.

**Comment by protogen** [comment]
A couple of other things...

If you login to the MyAussie portal, it also shows usage data.  My understanding is that that data is provided by the same mechanism the Rainmeter skin uses.  Check to see if the data is invalid there too.  This might help ABB investigate.

In the comments you added to the debug log, you stated "using full email address as UserName".  That is different to how I login.  I use the username provided by ABB (not an email address).  I really don't know what difference this could make though.  You're still obtaining a valid cookie, which would not be possible unless you were providing a correct username and password.  That said, give it a try using the username instead of the full email address and see what happens.

**Comment by subi75** [comment]
Just an update, I did raise a ticket to ABB Support, and had the following response:

<i><b>we're currently experiencing data update issues as it's broken ATM. I apologize for this inconvenience but these types of things are un-preventable unfortunately, we are making sure it's resolved as soon as possible.</i></b>

So I will close this as a vendor (ABB) based issue, and not a skin/code based issue.
